services:
  app:
    image: lihaozhe013/streamfile-server:latest
    container_name: streamfile-server-instance
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./files:/app/files
    ports:
      - "3000:3000"
    command: node server.js
